export {default as Navbar} from './navbar/Navbar'
export {default as Search} from './search/Search'
export {default as Foot} from './foot/Foot'
export {default as Card} from './card/Card'
export {default as Detailproject} from './detailproject/Detailproject'
// export {default as MouseTrail} from './mousetrail/MouseTrail'
